server:
  port: 8097
spring:
  config:
    import: optional:configserver:http//localhost:8091
  application:
    name: GatewaySever
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: AUTHSERVER
          uri: http://localhost:8096
          predicates:
            - Path=/auth/**
        - id: ACCOUNTSERVER
          uri: http://localhost:8095
          predicates:
            - Path=/account/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761